branches:
  only:
    - master
    - devel
    - /devel-.*/
    - /travis.*/
    - /ci-.*/

language: shell
os: linux
dist: bionic

env:
  jobs:
    - PYTHON=3.8.2
    - PYTHON=3.7.7
    - PYTHON=3.6.8
  global:
    - PYTHONWARNINGS="ignore::DeprecationWarning"
    - PIP_PROGRESS_BAR="off"
    - COVERALLS_PARALLEL=true

# Cache downloaded and built python packages
cache: pip

addons:
  apt:
    packages:
      - graphviz

before_install:
  - |
    # Install venv on Linux using Ubuntu distributed python
    # distutils and lib2to3 are only needed for python3.8
    # https://bugs.launchpad.net/ubuntu/+source/python3.8/+bug/1851684
    sudo apt-get install -y python${PYTHON%.*}-dev python${PYTHON%.*}-venv python3-distutils python3-lib2to3
    python${PYTHON%.*} -m venv $HOME/venv
    # Provide fake xdg-open
    echo "#!/bin/sh" > $HOME/venv/bin/xdg-open
    chmod +x $HOME/venv/bin/xdg-open

  # The rest of the setup is common for all environments
  - source $HOME/venv/bin/activate

  - python --version
  - pip install -U pip wheel
  - pip --version
  - |
    # Install undeclared dependencies
    if [ "x$EXTRA_PIP" != "x" ]; then
      pip install $EXTRA_PIP
    fi

install:
  - pip install coveralls
  - pip install git+https://github.com/benureau/leabra.git@master
  - pip install -e .[dev]


script:
  - if [ "x$RUN_COV" != "x" ] ; then echo "Running with coverage"; export COV_ARGS="--cov=psyneulink"; else echo "Running without coverage"; export COV_ARGS=""; fi
  - pytest -n auto -p no:logging $COV_ARGS

after_script:
  - if [ "x$RUN_COV" != "x" ] ; then coveralls; fi

notifications:
  webhooks: https://coveralls.io/webhook
